### ISSUE TITLE
Docker free autobuilds coming to an end

### ISSUE THREAD

**Issue by takluyver** [h5py/hdf5-manylinux#1]
This repo is currently built into images on Dockerhub, which was the path of least resistance when I set it up. I just had an email from Dockerhub saying that that's coming to an end (in 10 days :disappointed: ):

> As one of the users of Docker Hub’s Autobuild service, we wanted to reach out and let you know that from June 18th, 2021 users on the free plan will no longer have access to the Autobuild feature.

We could:

1. Apply to Docker's open source program. This takes me to a Google form asking about my 'job function' but not about which org I'm applying for. It doesn't give the impression that they understand much about small open source projects that don't have a company behind them.
2. Switch to another similar service, like Red Hat's quay.io, which still seems to do builds for free.
3. Build the image on e.g. Github actions & push it to one of these repositories which would just host the image.

@tacaswell, any preference, as you're also on the Docker org? I'm currently leaning towards 2.

**Comment by tacaswell** [comment]
If we go with 3 we could also use github container registry: https://github.blog/2020-09-01-introducing-github-container-registry/

**Comment by takluyver** [comment]
Good point. That also avoids having another account system to manage the container images. That's probably the simplest option, then. Are you happy with that?

**Comment by tacaswell** [comment]
I'm happy with it.  Reducing the number of services we have to keep track of seems like a net good.

**Comment by takluyver** [comment]
OK, the image is here: https://github.com/orgs/h5py/packages/container/package/manylinux2010_x86_64-hdf5

Now I'll make a PR to use it for h5py.
