### ISSUE TITLE
Consider keeping libaec and zib-devel in the image

### ISSUE THREAD

**Issue by ocefpaf** [h5py/hdf5-manylinux#10]
I understand that size if a concern but, if someone is using this image to build things on top of hdf5, those missing libraries would have to be re-installed. If the goal of this project does not cover re-use of the image, feel free to close this issue and I'll try to maintain a fork.

**Comment by aragilar** [comment]
This is really only for h5py to use for manylinux, my suggestion if you want something where you're running HDF5+h5py would be to construct your own image with an up-to-date HDF5 and with the features you want (ROS3 or MPI are obvious examples of things this image lacks).

**Comment by ocefpaf** [comment]
OK, fair enough. Ensuring compatibility and collaboration in the wheel ecosystem is quite hard! Thanks though. I'll fork it and create our another image.
