### ISSUE TITLE
ENH: Enable prerelease Python?

### ISSUE THREAD

**Issue by larsoner** [h5py/hdf5-manylinux#11]
I tried enabling prerelease pythons in https://github.com/h5py/h5py/actions/runs/9604936246/job/26491522927?pr=2444#step:11:329 but it failed because:
```
Error:   '/opt/python/cp313-cp313/bin/python' executable doesn't exist in image 'ghcr.io/h5py/manylinux2014_x86_64-hdf5' to build 'cp313-manylinux_x86_64'.
```
Is it possible to update the image to support 3.13? Maybe all that's needed is a new release of the image based on a newer base manylinux2014 image? (I'm a bit naive about all this stuff...)

**Comment by aragilar** [comment]
I've rerun the workflow so given we've not locked this to a specific hash of the upstream manylinux container, if 3.13 is in the latest one it should be available once the containers are built.

I wonder if it's worth doing a monthly build of this?

**Comment by larsoner** [comment]
Awesome, that worked! A monthly scheduled build would be great
