### ISSUE TITLE
MAINT: Update (again)

### ISSUE THREAD

**Issue by larsoner** [h5py/hdf5-manylinux#12]
Looks like CentOS7 mirrors are broken when using the manylinux image here, but fixed in `manylinux_2014:latest`:

https://github.com/pypa/manylinux/issues/1641

These appear to need to be regenerated, too.

**Comment by aragilar** [comment]
I presume rerunning the workflow is enough?

**Comment by larsoner** [comment]
Yeah I think that worked for #11!

**Comment by takluyver** [comment]
I see @aragilar re-ran it that day, and it's just running again now (picking up a newer HDF5), so I'm going to close this.
