### ISSUE TITLE
License

### ISSUE THREAD

**Issue by scemama** [h5py/hdf5-manylinux#3]
Hello,
I would like to make a fork of your project but I am not sure I can because there is no license. Could you please add a license?
Thanks!

**Comment by aragilar** [comment]
@takluyver can confirm, but you can assume that it should have the same [BSD](https://github.com/h5py/h5py/blob/master/LICENSE) license as h5py.

**Comment by takluyver** [comment]
Fine by me. Feel free to make a PR adding a license file if you want.

I'm not sure there's actually enough creative work here to be copyrightable, but it's easier to slap a BSD sticker on it than to waste time pondering that.

**Comment by scemama** [comment]
Great! Thanks
